### ISSUE TITLE
add possibility to check a hex-string

### ISSUE THREAD

**Issue by vbienf** [Deconkle/hacker-sim-scripts#1]
Hi! 

I downloaded and changed you script, and now it also can check the hex sting. How I can add this function to your script?

**Comment by Deconkle** [comment]
This should be easy to add, I will attempt to add this functionality later today.

A fellow community member shared a PowerShell script to convert hex strings [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2895103469).

**Comment by vbienf** [comment]
yeah, I saw it. But its better to work in one application, I wrote function something like this:

def get_hex_string(hex_string):
    hex_list = hex_string.split(":")
    normal_hex = ""
    for hex_part in hex_list:
        if all(c in string.hexdigits for c in hex_part):
            normal_hex = normal_hex + hex_part + ":"
    if len(normal_hex) < 1:
        print("HEX string didn't funded")
    else:
        normal_hex = normal_hex[:-1]
    print("Your HEX is " + normal_hex)

**Comment by Deconkle** [comment]
formatting
```py
def get_hex_string(hex_string):
    hex_list = hex_string.split(":")
    normal_hex = ""
    for hex_part in hex_list:
        if all(c in string.hexdigits for c in hex_part):
            normal_hex = normal_hex + hex_part + ":"
            if len(normal_hex) < 1:
                print("HEX string didn't funded")
            else:
                normal_hex = normal_hex[:-1]
                print("Your HEX is " + normal_hex)
```
